/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.hudi.analysis

import org.apache.hudi.common.schema.HoodieSchema

import org.apache.spark.ml.linalg.{DenseVector, Vectors}
import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.catalyst.plans.logical.HoodieVectorSearchTableValuedFunction.{DistanceMetric, SearchAlgorithm}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.apache.spark.sql.expressions.Window
import org.apache.spark.sql.functions.{broadcast, col, monotonically_increasing_id, row_number}
import org.apache.spark.sql.hudi.command.exception.HoodieAnalysisException
import org.apache.spark.sql.types.{ArrayType, ByteType, DataType, DoubleType, FloatType, StructField, StructType}

import scala.util.{Failure, Success, Try}

/**
 * Extension point for vector search algorithms. Each implementation provides
 * the Spark logical plan for single-query and batch-query KNN search.
 *
 * To add a new algorithm (e.g. RowMatrix, HNSW):
 *  1. Create an object extending this trait
 *  2. Add a value to [[SearchAlgorithm]]
 *  3. Register the mapping in [[HoodieVectorSearchPlanBuilder.resolveAlgorithm]]
 *
 * Implementations can use the shared validation helpers on
 * [[HoodieVectorSearchPlanBuilder]] (validateEmbeddingColumn, validateBatchDimensions, etc.)
 * and the raw distance functions on [[VectorDistanceUtils]].
 *
 * The output schema contract:
 *  - Single-query: all corpus columns (minus the embedding column) + `_hudi_distance: Double`
 *  - Batch-query: all corpus columns (minus the embedding column) + clashing query columns
 *    (prefixed with `_hudi_query_`) + `_hudi_distance: Double` + `_hudi_qid: Long`
 *  - Results are ordered by `_hudi_distance` ascending (lower = more similar)
 *  - `_hudi_qid` is an opaque grouping identifier (not a sequential index). Values may be
 *    large non-contiguous numbers because they are generated by `monotonically_increasing_id()`.
 */
trait VectorSearchAlgorithm {

  /** Human-readable name for error messages and logging. */
  def name: String

  /**
   * Build a plan that finds the k nearest corpus rows to a single query vector.
   *
   * @param spark          active SparkSession
   * @param corpusDf       resolved corpus DataFrame (may be Hudi, Parquet, or temp view)
   * @param embeddingCol   name of the array-typed embedding column in corpusDf
   * @param queryVector    the query vector, normalized to Array[Double]
   * @param k              number of nearest neighbors to return
   * @param metric         distance metric (COSINE, L2, DOT_PRODUCT)
   * @param filter         optional SQL predicate applied to the corpus before distance computation,
   *                       enabling partition pruning and data skipping.
   *                       String literals inside the predicate must use double quotes
   *                       (e.g. {@code label = "z-axis"}) because the filter is passed as a
   *                       single-quoted TVF argument and Spark's lexer does not support
   *                       {@code ''} as an escape sequence inside string literals.
   * @param maxDistance     optional distance threshold; results beyond this value are excluded
   * @return an analyzed LogicalPlan whose output matches the single-query schema contract
   */
  def buildSingleQueryPlan(
      spark: SparkSession,
      corpusDf: DataFrame,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      filter: Option[String] = None,
      maxDistance: Option[Double] = None): LogicalPlan

  /**
   * Build a plan that finds the k nearest corpus rows for each row in the query table.
   *
   * @param spark              active SparkSession
   * @param corpusDf           resolved corpus DataFrame
   * @param corpusEmbeddingCol name of the embedding column in corpusDf
   * @param queryDf            resolved query DataFrame
   * @param queryEmbeddingCol  name of the embedding column in queryDf
   * @param k                  number of nearest neighbors per query
   * @param metric             distance metric (COSINE, L2, DOT_PRODUCT)
   * @param filter             optional SQL predicate applied to the corpus before distance computation,
   *                           enabling partition pruning and data skipping
   * @param maxDistance         optional distance threshold; results beyond this value are excluded
   * @return an analyzed LogicalPlan whose output matches the batch-query schema contract
   * @note Batch mode broadcasts the query table to all executors via a cross-join.
   *       This is designed for small-to-medium query sets (tens to low hundreds of rows).
   *       For large query tables, memory pressure on executors may occur.
   */
  def buildBatchQueryPlan(
      spark: SparkSession,
      corpusDf: DataFrame,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      filter: Option[String] = None,
      maxDistance: Option[Double] = None): LogicalPlan
}

/**
 * Resolves [[SearchAlgorithm]] values to [[VectorSearchAlgorithm]] implementations
 * and provides shared validation helpers used across algorithms.
 */
object HoodieVectorSearchPlanBuilder {

  val DISTANCE_COL = "_hudi_distance"
  private[analysis] val QUERY_ID_COL = "_hudi_qid"
  private[analysis] val QUERY_EMB_ALIAS = "_hudi_query_emb"
  private[analysis] val RANK_COL = "_hudi_rank"
  private[analysis] val QUERY_COL_PREFIX = "_hudi_query_"

  /** Resolve a [[SearchAlgorithm]] enum value to its implementation. */
  def resolveAlgorithm(algorithm: SearchAlgorithm.Value): VectorSearchAlgorithm = algorithm match {
    case SearchAlgorithm.BRUTE_FORCE => BruteForceSearchAlgorithm
    case other => throw new HoodieAnalysisException(
      s"Unsupported search algorithm: $other")
  }

  private[analysis] def validateEmbeddingColumn(df: DataFrame, colName: String): Unit = {
    val fieldOpt = df.schema.fields.find(_.name == colName)
    val field = fieldOpt.getOrElse(
      throw new HoodieAnalysisException(
        s"Embedding column '$colName' not found in table schema. " +
          s"Available columns: ${df.schema.fieldNames.mkString(", ")}"))
    field.dataType match {
      case ArrayType(FloatType, _) | ArrayType(DoubleType, _) | ArrayType(ByteType, _) => // valid
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, " +
            "expected array<float>, array<double>, or array<byte>")
    }
  }

  /**
   * Validates that the query vector dimension matches the corpus embedding dimension
   * when the corpus column has VECTOR(dim) metadata.
   */
  private[analysis] def validateQueryVectorDimension(
      df: DataFrame, embeddingCol: String, queryDim: Int): Unit = {
    extractVectorDimension(df, embeddingCol).foreach { corpusDim =>
      if (corpusDim != queryDim) {
        throw new HoodieAnalysisException(
          s"Query vector dimension ($queryDim) does not match " +
            s"corpus embedding dimension ($corpusDim) for column '$embeddingCol'")
      }
    }
  }

  /**
   * Validates that corpus and query embedding columns have the same element type.
   */
  private[analysis] def validateElementTypeCompatibility(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    val corpusElemType = getElementType(corpusDf, corpusCol)
    val queryElemType = getElementType(queryDf, queryCol)
    if (corpusElemType != queryElemType) {
      throw new HoodieAnalysisException(
        s"Corpus embedding column '$corpusCol' has element type $corpusElemType " +
          s"but query embedding column '$queryCol' has element type $queryElemType. " +
          "Both must use the same element type (e.g. array<float>).")
    }
  }

  /**
   * Validates that corpus and query embedding dimensions match when both have
   * VECTOR(dim) metadata.
   */
  private[analysis] def validateBatchDimensions(
      corpusDf: DataFrame, corpusCol: String,
      queryDf: DataFrame, queryCol: String): Unit = {
    (extractVectorDimension(corpusDf, corpusCol), extractVectorDimension(queryDf, queryCol)) match {
      case (Some(corpusDim), Some(queryDim)) if corpusDim != queryDim =>
        throw new HoodieAnalysisException(
          s"Corpus embedding dimension ($corpusDim) does not match " +
            s"query embedding dimension ($queryDim)")
      case _ => // dimensions match or metadata not available
    }
  }

  private[analysis] def getElementType(df: DataFrame, colName: String): DataType = {
    df.schema(colName).dataType match {
      case ArrayType(elemType, _) => elemType
      case other =>
        throw new HoodieAnalysisException(
          s"Embedding column '$colName' has type $other, expected an array type")
    }
  }

  /** Extracts VECTOR(dim) dimension from column metadata, if present. */
  private def extractVectorDimension(df: DataFrame, colName: String): Option[Int] = {
    df.schema.fields.find(_.name == colName).flatMap { field =>
      val meta = field.metadata
      if (meta.contains(HoodieSchema.TYPE_METADATA_FIELD)) {
        val typeDesc = meta.getString(HoodieSchema.TYPE_METADATA_FIELD)
        Try(HoodieSchema.parseTypeDescriptor(typeDesc)) match {
          case Success(v: HoodieSchema.Vector) => Some(v.getDimension)
          case Success(_) => None
          case Failure(e) => throw new HoodieAnalysisException(
            s"Column '$colName' has malformed type metadata '$typeDesc': ${e.getMessage}")
        }
      } else None
    }
  }
}

/**
 * Brute-force KNN vector search: computes distance between every corpus row and
 * every query vector, then selects the top-K closest.
 *
 * <p>Complexity: O(|corpus| * |queries| * dimensions) — linear scan with no index.
 *
 * <p><b>Single-query mode:</b> uses {@code mapPartitions} with buffer reuse to compute
 * distances at the partition level, eliminating per-row UDF overhead and GC pressure.
 * A reusable {@code DenseVector} wrapping a mutable {@code Array[Double]} is allocated
 * once per partition. Results use {@code orderBy + limit(k)} (Spark optimizes this to
 * a partial sort via TakeOrderedAndProject).
 *
 * <p><b>Batch-query mode:</b> broadcast cross-joins the (small) query table with
 * the corpus, computes pairwise distances via UDF, then uses a window function to rank
 * and select top-K per query. The cross-join produces O(|corpus| * |queries|)
 * intermediate rows, so this is suitable for small-to-medium query sets
 * (tens to low hundreds of queries) against moderate corpora.
 *
 * <p>Both modes support an optional {@code filter} predicate (applied to the corpus before
 * distance computation, enabling Hudi partition pruning and data skipping) and an optional
 * {@code maxDistance} threshold (results beyond this distance are excluded before top-K
 * selection, reducing shuffle and sort volume).
 */
object BruteForceSearchAlgorithm extends VectorSearchAlgorithm {

  import HoodieVectorSearchPlanBuilder._

  override val name: String = "brute_force"

  /**
   * Parses and resolves a SQL filter predicate against the DataFrame's schema using the
   * session-aware parser, then applies it. This avoids the pitfall of
   * {@code DataFrame.filter(String)} which internally uses {@code SparkSession.active}
   * (potentially a different session inside Catalyst analyzer rules).
   */
  private def applyFilter(spark: SparkSession, df: DataFrame, filterExpr: String): DataFrame = {
    try {
      df.filter(filterExpr)
    } catch {
      case e: Exception =>
        throw new HoodieAnalysisException(
          s"Invalid pre-filter expression '$filterExpr': ${e.getMessage}")
    }
  }

  override def buildSingleQueryPlan(
      spark: SparkSession,
      corpusDf: DataFrame,
      embeddingCol: String,
      queryVector: Array[Double],
      k: Int,
      metric: DistanceMetric.Value,
      filter: Option[String] = None,
      maxDistance: Option[Double] = None): LogicalPlan = {
    validateEmbeddingColumn(corpusDf, embeddingCol)
    validateQueryVectorDimension(corpusDf, embeddingCol, queryVector.length)

    val elemType = getElementType(corpusDf, embeddingCol)

    // Apply pre-filter before distance computation to enable Hudi partition pruning
    // and data skipping, reducing the number of rows that need distance computation.
    var baseDf = corpusDf.filter(col(embeddingCol).isNotNull)
    filter.foreach(f => baseDf = applyFilter(spark, baseDf, f))

    // Validate byte corpus query vector values before computing distances.
    if (elemType == ByteType) {
      queryVector.foreach { v =>
        if (v < Byte.MinValue || v > Byte.MaxValue)
          throw new HoodieAnalysisException(
            s"Query vector value $v is out of range for byte corpus [${Byte.MinValue}, ${Byte.MaxValue}]")
        if (v != v.toByte.toDouble)
          throw new HoodieAnalysisException(
            s"Query vector value $v is not a whole number. " +
              "Byte corpus embeddings require integer-valued query vectors.")
      }
    }

    val inputSchema = baseDf.schema
    val embeddingIdx = inputSchema.fieldIndex(embeddingCol)
    val keepIndices = inputSchema.fields.indices.filter(_ != embeddingIdx).toArray
    val outputSchema = StructType(
      keepIndices.map(inputSchema.fields(_)) :+ StructField(DISTANCE_COL, DoubleType, nullable = false))

    // Capture serializable values for the closure — these are sent to executors.
    val queryArr = queryVector.clone()
    val dims = queryArr.length
    val metricValue = metric
    val corpusElemType = elemType

    val distanceRdd = baseDf.rdd.mapPartitions { iter =>
      // Allocate buffer once per partition; DenseVector wraps it without copying.
      val buffer = new Array[Double](dims)
      val corpusDv = new DenseVector(buffer)
      val queryDv = new DenseVector(queryArr)
      val queryNorm = Vectors.norm(queryDv, 2.0)
      val distFn = VectorDistanceUtils.resolveDistanceFn(metricValue)

      // Specialize the fill function once per partition based on element type.
      val fillBuffer: (Row, Int) => Unit = corpusElemType match {
        case FloatType => (row, idx) =>
          val seq = row.getSeq[Float](idx)
          VectorDistanceUtils.requireSameLength(seq.length, dims)
          var i = 0; while (i < dims) { buffer(i) = seq(i).toDouble; i += 1 }
        case DoubleType => (row, idx) =>
          val seq = row.getSeq[Double](idx)
          VectorDistanceUtils.requireSameLength(seq.length, dims)
          var i = 0; while (i < dims) { buffer(i) = seq(i); i += 1 }
        case ByteType => (row, idx) =>
          val seq = row.getSeq[Byte](idx)
          VectorDistanceUtils.requireSameLength(seq.length, dims)
          var i = 0; while (i < dims) { buffer(i) = seq(i).toDouble; i += 1 }
      }

      iter.map { row =>
        fillBuffer(row, embeddingIdx)
        val dist = distFn(corpusDv, queryDv, queryNorm)
        Row.fromSeq(keepIndices.map(row.get) :+ dist)
      }
    }

    var resultDf = spark.createDataFrame(distanceRdd, outputSchema)
    maxDistance.foreach(d => resultDf = resultDf.filter(col(DISTANCE_COL) <= d))
    val result = resultDf.orderBy(col(DISTANCE_COL).asc).limit(k)

    result.queryExecution.analyzed
  }

  override def buildBatchQueryPlan(
      spark: SparkSession,
      corpusDf: DataFrame,
      corpusEmbeddingCol: String,
      queryDf: DataFrame,
      queryEmbeddingCol: String,
      k: Int,
      metric: DistanceMetric.Value,
      filter: Option[String] = None,
      maxDistance: Option[Double] = None): LogicalPlan = {
    validateEmbeddingColumn(corpusDf, corpusEmbeddingCol)
    validateEmbeddingColumn(queryDf, queryEmbeddingCol)
    validateElementTypeCompatibility(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)
    validateBatchDimensions(corpusDf, corpusEmbeddingCol, queryDf, queryEmbeddingCol)

    val corpusElemType = getElementType(corpusDf, corpusEmbeddingCol)
    val distanceUdf = VectorDistanceUtils.createDistanceUdf(metric, corpusElemType)

    // Apply pre-filter before cross-join to enable Hudi partition pruning
    // and data skipping, reducing the cross-join cardinality.
    var filteredCorpus = corpusDf.filter(col(corpusEmbeddingCol).isNotNull)
    filter.foreach(f => filteredCorpus = applyFilter(spark, filteredCorpus, f))

    // Prefix clashing query columns with "_hudi_query_" to avoid cross-join ambiguity when
    // corpus and query share column names (e.g. both have "id" or "embedding").
    // QUERY_ID_COL uses a distinct name (_hudi_qid) so it never clashes with prefixed query cols.
    val corpusCols = filteredCorpus.columns.toSet
    val queryWithId = queryDf.filter(col(queryEmbeddingCol).isNotNull)
      .withColumnRenamed(queryEmbeddingCol, QUERY_EMB_ALIAS)
      .withColumn(QUERY_ID_COL, monotonically_increasing_id())

    val renamedQuery = queryWithId.select(queryWithId.columns.map { qCol =>
      if (qCol != QUERY_ID_COL && qCol != QUERY_EMB_ALIAS && corpusCols.contains(qCol))
        col(qCol).as(s"$QUERY_COL_PREFIX$qCol")
      else
        col(qCol)
    }: _*)

    // Cross join corpus with broadcast queries, compute distance, then rank
    var scored = filteredCorpus.crossJoin(broadcast(renamedQuery))
      .withColumn(DISTANCE_COL,
        distanceUdf(col(corpusEmbeddingCol), col(QUERY_EMB_ALIAS)))
      .drop(corpusEmbeddingCol)
      .drop(QUERY_EMB_ALIAS)

    // Apply max distance threshold before windowing to reduce shuffle volume.
    maxDistance.foreach(d => scored = scored.filter(col(DISTANCE_COL) <= d))

    val window = Window.partitionBy(QUERY_ID_COL).orderBy(col(DISTANCE_COL).asc)
    val result = scored
      .withColumn(RANK_COL, row_number().over(window))
      .filter(col(RANK_COL) <= k)
      .drop(RANK_COL)
      .orderBy(col(QUERY_ID_COL), col(DISTANCE_COL))

    result.queryExecution.analyzed
  }

}
